### ISSUE TITLE
Support for Umbraco 7.14

### ISSUE THREAD

**Issue by tristanjthompson** [stevemegson/PreMigrationHealthChecks#1]
Hi,

First of all, thank you for writing and open-sourcing this!

We are migrating from 7.14 (long story, but we've gone to this version as it's the minimum required for content migration to v8) and I wanted to run your package, however, I noticed that the minimum version of Umbraco required on your package was 7.15.3

I downloaded the source from here, downgraded the nuget version of Umbraco required to 7.14 and referenced it in my Umbraco project.  It seems to run with no issues.

Is there a particular reason that you've done it against 7.15.3?  Do you see any reason why it won't support 7.14+, or is it because you have built it against 7.15.3 and haven't had a chance to run it against lower versions?

I'd be happy to create a PR with the change I made to downgrade the nuget version of Umbraco(obviously very small!)

**Comment by stevemegson** [comment]
Hi,

That's a very good point. I think I was working against 7.15.3 because there are some database migrations between 7.14 and 7.15, and I wanted to be sure that everything worked with a fully-upgraded database. I don't think there should be any problems using it with 7.14.x, though.

I've updated the nuget version and uploaded a new version of the package.

**Comment by tristanjthompson** [comment]
Awesome - that's great work @stevemegson - thank you! #h5yr
